package org.model;

import java.util.*;

public class Bundle {
    public Commented<String> operator = new Commented<>("Mutation operator identifier, e.g., AOR, AOIU, ROR");
    public Commented<String> diff = new Commented<>(
            "Minimal syntactic difference at mutation point between original and mutant");
    public CommentedList<String> domainAssumptions = new CommentedList<String>(
            "Assumptions/constraints for equivalence (e.g., \"only compare return value\", \"no external side effects\", \"input range constraint\")");
    public CommentedList<String> specObserved = new CommentedList<String>(
            "Set of observable points (sinks), constraining whether propagation is observable (e.g., return/exception/state)");
    public CommentedList<String> jimpleChanges = new CommentedList<String>(
            "Summary of affected Jimple statements and mutation diffs (with line numbers), for aligning original and mutant");

    public static class Commented<T> {
        public String comment;
        public T item;

        public Commented() {
        }

        public Commented(String comment) {
            this.comment = comment;
        }

        public Commented(String comment, T item) {
            this.comment = comment;
            this.item = item;
        }
    }

    public static class CommentedList<T> {
        public String comment;
        public List<T> items = new ArrayList<>();

        public CommentedList() {
        }

        public CommentedList(String comment) {
            this.comment = comment;
            this.items = new ArrayList<>();
        }

        public CommentedList(String comment, List<T> items) {
            this.comment = comment;
            this.items = items;
        }

        public void add(T item) {
            this.items.add(item);
        }
    }

    public Commented<Side> origin = new Commented<>("Original", new Side());
    public Commented<Side> mutant = new Commented<>("Mutant", new Side());

    public static class Side {
        public Commented<String> id = new Commented<String>("Program ID");
        public Commented<String> content = new Commented<String>("Method text content");
        public Commented<String> IR = new Commented<String>(
                "Jimple intermediate representation of method body, generated by Soot framework");
        public CommentedList<String> Affected = new CommentedList<String>(
                "Set of affected Jimple elements: intermediate statements influenced by mutation point");
        public CommentedList<String> Paths = new CommentedList<String>(
                "Set of affected paths: all valid control flow paths crossing mutation point, each containing all statements in Affected");
        public CommentedList<Info.InfoItem> CPG = new CommentedList<>(
                "CFG and DFG info related to mutation-point paths, forming a Code Property Graph (CPG)");
    }
}
